---
title: "Species Distribution Modeling using Spatial Point Processes: a Case Study of Sloths in Costa Rica"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```

Full case study here: https://www.paulamoraga.com/tutorial-point-patterns/#

### Reading in the data

```{r}

#install.packages("spocc")
library('spocc')
df <- occ(query = 'Bradypus variegatus', from = 'gbif',
          date = c("2000-01-01", "2019-12-31"),
          gbifopts = list(country = "CR"),
          has_coords = TRUE, limit = 1000)

names(df)
d <- occ2df(df)
summary(d)

```

### Working with the 'sp' library

Extracting spatial coordinates. 

```{r}

library(sp)
dpts <- SpatialPoints(d[, c("longitude", "latitude")])

dpts@coords

```

Plotting the locations of the sloths

```{r}

library(tmap)
tmap_mode("view")
tm_basemap(leaflet::providers$OpenStreetMap) + tm_shape(dpts) + tm_dots()

```


### Covariates 

```{r}

library(raster)
rmonth <- getData(name = "worldclim", var = "tmin", res = 10)
rcov <- mean(rmonth)

```

### Grid 

```{r}

#install.packages("rnaturalearth")
#install.packages("rnaturalearthdata")

library(rnaturalearth)
library(rnaturalearthdata)

map <- ne_countries(type = "countries", country = "Costa Rica", scale = "medium")

```

```{r}

resolution <- 0.1
r <- raster(map, resolution = resolution)
(nrow <- nrow(r))
(ncol <- ncol(r))
nrow*ncol

r[] <- 0
tab <- table(cellFromXY(r, dpts))
tab

r[as.numeric(names(tab))] <- tab
## Raster to polygon
grid <- rasterToPolygons(r)

```

```{r}

grid$id <- 1:nrow(grid)
grid$Y <- grid$layer
grid$cellarea <- resolution*resolution

grid$cov <- raster::extract(rcov, coordinates(grid))

gridmap <- raster::intersect(grid, map)
grid <- grid[grid$id %in% gridmap$id, ]

summary(grid)
```


#### Missing Covariates

```{r}

indNA <- which(is.na(grid$cov))
indNA

grid$cov[indNA] <- grid$cov[indNA+1]

library(rgeos)
gridborder <- gUnaryUnion(grid)

```


### Numbers of Sloths and Covariate Maps

```{r}

tmap_mode("plot")
tm_shape(grid) +
  tm_polygons(col = c("Y", "cov"), border.col = "transparent") +
  tm_shape(gridborder) + tm_borders() +
  tm_facets(ncol = 2) + tm_legend(legend.position = c("left", "bottom"))

```

### Fitting the model in INLA

```{r}

library(INLA)

grid$id2 <- grid$id

## formula in INLA for a spatial point process model
## Y = sloth counts
formula <- Y ~ 1 + cov +
  f(id, model="rw2d", nrow = nrow, ncol = ncol) +
  f(id2, model="iid")

## f(id, model="rw2d", nrow = nrow, ncol = ncol) -- structured random effect (spatial random effect)
##  f(id2, model="iid") -- unstructured random effect

res <- inla(formula, family = "poisson", data = grid@data, E = cellarea, control.predictor = list(compute = TRUE))

summary(res)
```

#### Plotting the results

```{r}

library(ggplot2)
marginal <- inla.smarginal(res$marginals.fixed$cov)
marginal <- data.frame(marginal)
ggplot(marginal, aes(x = x, y = y)) + geom_line() +
  labs(x = expression(beta[1]), y = "Density") +
  geom_vline(xintercept = 0, col = "black") + theme_bw()

```

```{r}

nrow(res$summary.random$id)
grid$respa <- res$summary.random$id[grid$id, "mean"]
grid$reiid <- res$summary.random$id2[, "mean"]

tm_shape(grid) +
  tm_polygons(col = c("respa", "reiid"), style = "cont", border.col = "transparent")  +
  tm_shape(gridborder) + tm_borders() +
  tm_facets(ncol = 2) + tm_legend(legend.position = c("left", "bottom"))

```

```{r}

cellarea <- resolution*resolution
grid$NE <- res$summary.fitted.values[, "mean"] * cellarea
grid$LL <- res$summary.fitted.values[, "0.025quant"] * cellarea
grid$UL <- res$summary.fitted.values[, "0.975quant"] * cellarea
summary(grid)

```

```{r}

tm_shape(grid) +
  tm_polygons(col = c("NE", "LL", "UL"),
              style = 'fixed', border.col = "transparent",
              breaks = seq(0, ceiling(max(grid$UL)), 10)) +
  tm_shape(gridborder) + tm_borders() +
  tm_facets(ncol = 3) + tm_legend(legend.position = c("left", "bottom")) 

```